<a href="https://colab.research.google.com/github/greeshmaunni1990/PyTorch-For-ML-DL/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print('HEllo world')

HEllo world


In [3]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors

**Creating tensors**

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item()

7

In [9]:
# vector
vector = torch.tensor([7, 7])

In [10]:
# dimension can be easily calculated by the number of square brackets.
# if it is has one square brack then it is 1-D
# if it has two square brack then it is 2-D

vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [13]:
MATRIX.dtype

torch.int64

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[0]

tensor([1, 2])

In [16]:
MATRIX[1]

tensor([3, 4])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [5, 7, 3],
                        [11, 58, 36]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 5,  7,  3],
         [11, 58, 36]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR = torch.tensor([[[[[[2, 11, 36.5], [58, 33, 26]]]]]])
TENSOR

tensor([[[[[[ 2.0000, 11.0000, 36.5000],
            [58.0000, 33.0000, 26.0000]]]]]])

In [22]:
TENSOR.shape

torch.Size([1, 1, 1, 1, 2, 3])

### Random Tensors

Random numbers are important bacause the way manu neural networks learn is that they start with tensors full of random numbers and then they adjust these random numbers to better represent data
```
Start with random numbers -> look at data -> update random numbers -> look at data > update random numers
```




In [23]:
# create random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6564, 0.4078, 0.4717, 0.3132],
        [0.0517, 0.8721, 0.0978, 0.6252],
        [0.4222, 0.6316, 0.0203, 0.7917]])

In [24]:
random_tensor.ndim

2

In [30]:
# create random tensors
random_tensor = torch.rand(4, 3, 4)
random_tensor

tensor([[[0.0975, 0.8063, 0.9428, 0.6265],
         [0.6757, 0.4921, 0.3412, 0.2047],
         [0.7935, 0.2840, 0.1878, 0.3734]],

        [[0.6485, 0.4742, 0.5748, 0.2829],
         [0.5182, 0.1744, 0.4085, 0.9316],
         [0.2494, 0.5573, 0.0053, 0.6465]],

        [[0.4433, 0.0586, 0.4312, 0.1071],
         [0.3413, 0.0656, 0.4791, 0.4870],
         [0.8907, 0.7334, 0.6390, 0.4084]],

        [[0.4069, 0.1988, 0.3388, 0.2253],
         [0.7557, 0.6992, 0.6710, 0.0964],
         [0.1838, 0.7802, 0.7203, 0.2352]]])

In [26]:
random_tensor.ndim

3

In [27]:
# create random tesnor with same shape as that of an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [31]:
# Create tensor of all zero
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [33]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones * random_tensor

tensor([[[0.0975, 0.8063, 0.9428, 0.6265],
         [0.6757, 0.4921, 0.3412, 0.2047],
         [0.7935, 0.2840, 0.1878, 0.3734]],

        [[0.6485, 0.4742, 0.5748, 0.2829],
         [0.5182, 0.1744, 0.4085, 0.9316],
         [0.2494, 0.5573, 0.0053, 0.6465]],

        [[0.4433, 0.0586, 0.4312, 0.1071],
         [0.3413, 0.0656, 0.4791, 0.4870],
         [0.8907, 0.7334, 0.6390, 0.4084]],

        [[0.4069, 0.1988, 0.3388, 0.2253],
         [0.7557, 0.6992, 0.6710, 0.0964],
         [0.1838, 0.7802, 0.7203, 0.2352]]])

### Create range of tensors and tensors-like

In [42]:
# create range
torch_range = torch.arange(0, 5)

# create a step 
torch_range_step = torch.arange(start=0, end=500, step=10)

In [43]:
torch_range_step.shape

torch.Size([50])

In [46]:
#create a zero tensor that will be similar to the input
tensor_zeros_like = torch.zeros_like(input=torch_range_step)
tensor_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [48]:
#create a ones tensor that will be similar to the input
tensor_ones_like = torch.ones_like(input=torch_range_step)
tensor_ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])

### Tensor Datatype

1. Always check if the tensors are the right datatype
2. Always check if the tensors are the rigth shape
3. Always check if the tensors is on thr right device

In [54]:
 # default data type is float 32
 # dtype=torch.float16 will convert the data type to float 16
 # float32 means the numbers are stored in 32 bit
 # float16 means the numbers are stored in 16 bit
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype=torch.float16)

# dtype = None will take the default data type which is float32
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype=None)

In [55]:
float_32_tensor.dtype

torch.float32

In [57]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype=None,
                               device=None, # what gradient your tensor is on
                               requires_grad=True)# whether or not to track gradients with tensor operations

In [58]:
# convert float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

### Getting info from Tensor(Tensor Attributes)

1. Always check if the tensors are the right datatype- check `tensor.dtype`
2. Always check if the tensors are the rigth shape - check `tensor.shape`
3. Always check if the tensors is on thr right device - check `tensor.device`

In [66]:
tensor_one = torch.rand(4, 3)
tensor_one

tensor([[0.1649, 0.5882, 0.7479],
        [0.7252, 0.4466, 0.9530],
        [0.4517, 0.5434, 0.4018],
        [0.4886, 0.1315, 0.4849]])

In [68]:
print(f'tensor data type is {tensor_one.dtype}')
print(f'tensor shape is {tensor_one.shape}')
print(f'tensor device is {tensor_one.device}')

tensor data type is torch.float32
tensor shape is torch.Size([4, 3])
tensor device is cpu


### Manipulating Tensors

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [69]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [70]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [71]:
 #subtraction
tensor - 10

tensor([-9, -8, -7])

In [73]:
# pytorch built-in functions
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [74]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two type of multiplication used in neural networks and deep learning is:
1. Element-wise multiplication
2. Matrix- Multiplicaiton(dot-product)

In [75]:
# Element wise multiplication
print('element multiplication is', tensor * tensor)

element multiplication is tensor([1, 4, 9])


In [76]:
# Matrix Multiplication
print('Matrix multiplication is', torch.matmul(tensor, tensor))

Matrix multiplication is tensor(14)


In [77]:
# @ stands for matrix multiplication
tensor @ tensor

tensor(14)

### Criteria Matrix multplication should comply

1. Inner dimensions should match

```
(3, 2) @ (3, 2) won't work
(3, 2) @ (2, 3) will work
(2, 3) @ (3, 2) will work
```
2. The shape of the resulting matrix should be equal to outer dimensions


```
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
```

