<a href="https://colab.research.google.com/github/greeshmaunni1990/PyTorch-For-ML-DL/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('HEllo world')

HEllo world


In [ ]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors

**Creating tensors**

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])

In [ ]:
# dimension can be easily calculated by the number of square brackets.
# if it is has one square brack then it is 1-D
# if it has two square brack then it is 2-D

vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.dtype

torch.int64

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [5, 7, 3],
                        [11, 58, 36]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 5,  7,  3],
         [11, 58, 36]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[[[[2, 11, 36.5], [58, 33, 26]]]]]])
TENSOR

tensor([[[[[[ 2.0000, 11.0000, 36.5000],
            [58.0000, 33.0000, 26.0000]]]]]])

In [ ]:
TENSOR.shape

torch.Size([1, 1, 1, 1, 2, 3])

### Random Tensors

Random numbers are important bacause the way manu neural networks learn is that they start with tensors full of random numbers and then they adjust these random numbers to better represent data
```
Start with random numbers -> look at data -> update random numbers -> look at data > update random numers
```




In [ ]:
# create random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2027, 0.6860, 0.9373, 0.9115],
        [0.9709, 0.1504, 0.7625, 0.3183],
        [0.0434, 0.1458, 0.7102, 0.0203]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create random tensors
random_tensor = torch.rand(4, 3, 4)
random_tensor

tensor([[[0.7378, 0.6342, 0.7029, 0.6875],
         [0.7858, 0.1678, 0.5170, 0.1314],
         [0.3854, 0.3148, 0.8906, 0.6882]],

        [[0.7815, 0.5354, 0.2579, 0.2603],
         [0.0425, 0.1977, 0.0928, 0.0935],
         [0.2352, 0.7052, 0.3832, 0.3164]],

        [[0.1687, 0.2091, 0.9815, 0.8473],
         [0.3140, 0.4508, 0.4458, 0.7949],
         [0.2347, 0.4535, 0.7608, 0.1371]],

        [[0.0275, 0.1198, 0.3730, 0.4206],
         [0.7672, 0.3947, 0.2862, 0.3216],
         [0.3572, 0.9318, 0.2309, 0.7188]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create random tesnor with same shape as that of an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create tensor of all zero
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones * random_tensor

tensor([[[0.7378, 0.6342, 0.7029, 0.6875],
         [0.7858, 0.1678, 0.5170, 0.1314],
         [0.3854, 0.3148, 0.8906, 0.6882]],

        [[0.7815, 0.5354, 0.2579, 0.2603],
         [0.0425, 0.1977, 0.0928, 0.0935],
         [0.2352, 0.7052, 0.3832, 0.3164]],

        [[0.1687, 0.2091, 0.9815, 0.8473],
         [0.3140, 0.4508, 0.4458, 0.7949],
         [0.2347, 0.4535, 0.7608, 0.1371]],

        [[0.0275, 0.1198, 0.3730, 0.4206],
         [0.7672, 0.3947, 0.2862, 0.3216],
         [0.3572, 0.9318, 0.2309, 0.7188]]])

### Create range of tensors and tensors-like

In [ ]:
# create range
torch_range = torch.arange(0, 5)

# create a step 
torch_range_step = torch.arange(start=0, end=500, step=10)

In [ ]:
torch_range_step.shape

torch.Size([50])

In [ ]:
#create a zero tensor that will be similar to the input
tensor_zeros_like = torch.zeros_like(input=torch_range_step)
tensor_zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [ ]:
#create a ones tensor that will be similar to the input
tensor_ones_like = torch.ones_like(input=torch_range_step)
tensor_ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1])

### Tensor Datatype

1. Always check if the tensors are the right datatype
2. Always check if the tensors are the rigth shape
3. Always check if the tensors is on thr right device

In [ ]:
 # default data type is float 32
 # dtype=torch.float16 will convert the data type to float 16
 # float32 means the numbers are stored in 32 bit
 # float16 means the numbers are stored in 16 bit
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype=torch.float16)

# dtype = None will take the default data type which is float32
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype=None)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 4.0, 5.0], dtype=None,
                               device=None, # what gradient your tensor is on
                               requires_grad=True)# whether or not to track gradients with tensor operations

In [ ]:
# convert float32 to float16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 4., 5.], dtype=torch.float16, grad_fn=<ToCopyBackward0>)

### Getting info from Tensor(Tensor Attributes)

1. Always check if the tensors are the right datatype- check `tensor.dtype`
2. Always check if the tensors are the rigth shape - check `tensor.shape`
3. Always check if the tensors is on thr right device - check `tensor.device`

In [ ]:
tensor_one = torch.rand(4, 3)
tensor_one

tensor([[0.6156, 0.3754, 0.7893],
        [0.3555, 0.6894, 0.8608],
        [0.7269, 0.7886, 0.3548],
        [0.9023, 0.6670, 0.3860]])

In [ ]:
print(f'tensor data type is {tensor_one.dtype}')
print(f'tensor shape is {tensor_one.shape}')
print(f'tensor device is {tensor_one.device}')

tensor data type is torch.float32
tensor shape is torch.Size([4, 3])
tensor device is cpu


### Manipulating Tensors

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication


In [ ]:
# Addition
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
 #subtraction
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# pytorch built-in functions
torch.mul(tensor , 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two type of multiplication used in neural networks and deep learning is:
1. Element-wise multiplication
2. Matrix- Multiplicaiton(dot-product)

In [ ]:
# Element wise multiplication
print('element multiplication is', tensor * tensor)

element multiplication is tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
print('Matrix multiplication is', torch.matmul(tensor, tensor))

Matrix multiplication is tensor(14)


In [ ]:
# @ stands for matrix multiplication
tensor @ tensor

tensor(14)

### Criteria Matrix multplication should comply

1. Inner dimensions should match

```
(3, 2) @ (3, 2) won't work
(3, 2) @ (2, 3) will work
(2, 3) @ (3, 2) will work
```
2. The shape of the resulting matrix should be equal to outer dimensions


```
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
```



### Most common error of DL is shape errors

To fix shape errors, manipulate the shape of the tensors using **transpose**

A **transpose** will switch the axes or dimensions of the given tensor

In [ ]:
tensor_A = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])

tensor_B = torch.tensor([[7, 8, 9],
                         [10, 11, 12]])

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [ ]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
# to re arrange the shape, we can take the transpose of tensor_B and matrix multiply it
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 50,  68],
        [122, 167]])

### Tensor Aggregation

Finding the min, max, mean ans sum of tensors

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
# we can use both the methods to find  the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean
#note: we have to convert the tensor to float32 to make the mean work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Find the position of min and max

In [ ]:
# find the index where the minimum value of the tensor is positioned
x.argmin()

tensor(0)

In [ ]:
# find the index where the minimum value of the tensor is positioned
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return view of input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - remove `1 dimensions` from tensor
* Unsqueeze - add `1 dimension` to a target tensor
* Permute - Return a view of the input with dimensions permuted(swappped) in a certain way 

In [ ]:
x = torch.arange(1, 10)
x, x.shape, x.ndim

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]), 1)

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]), 2)

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
# view will share the same memory location as that of x. ie, any change made in z will change x
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
# stacking tensors
# dim = 0 will stack the tensor vertically
x_stac_vert = torch.stack([x, x, x], dim=0)
x_stac_vert

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# dim = 1 will stack the tensor horizontally
x_stack_hor= torch.stack([x, x, x], dim=1)
x_stack_hor

tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

### PyTorch tensors and Numpy

Numpy is a scientific computing library
* To convert fro numpy to tensor `torch.from_numpy(ndarray)`
* To convert a tensosr to numpy torch.Tensor.numpy()

In [ ]:
# convert numpy to tensor
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

# Here the data type when converted from numpy to tensor is changed from float32
# to float64


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# to convert the float32 to float64
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32