<a href="https://colab.research.google.com/github/greeshmaunni1990/PyTorch-For-ML-DL/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print('HEllo world')

HEllo world


In [2]:
!nvidia-smi

Mon Oct 24 08:49:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors

**Creating tensors**

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7, 7])

In [9]:
# dimension can be easily calculated by the number of square brackets.
# if it is has one square brack then it is 1-D
# if it has two square brack then it is 2-D

vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [12]:
MATRIX.dtype

torch.int64

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[0]

tensor([1, 2])

In [15]:
MATRIX[1]

tensor([3, 4])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [5, 7, 3],
                        [11, 58, 36]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 5,  7,  3],
         [11, 58, 36]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR = torch.tensor([[[[[[2, 11, 36.5], [58, 33, 26]]]]]])
TENSOR

tensor([[[[[[ 2.0000, 11.0000, 36.5000],
            [58.0000, 33.0000, 26.0000]]]]]])

In [22]:
TENSOR.shape

torch.Size([1, 1, 1, 1, 2, 3])

### Random Tensors

Random numbers are important bacause the way manu neural networks learn is that they start with tensors full of random numbers and then they adjust these random numbers to better represent data
```
Start with random numbers -> look at data -> update random numbers -> look at data > update random numers
```




In [23]:
# create random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4470, 0.4208, 0.8038, 0.9230],
        [0.4689, 0.4047, 0.1327, 0.4038],
        [0.2517, 0.3737, 0.3540, 0.7991]])

In [24]:
random_tensor.ndim

2

In [25]:
# create random tensors
random_tensor = torch.rand(4, 3, 2)
random_tensor

tensor([[[0.7226, 0.1230],
         [0.1864, 0.7729],
         [0.8238, 0.7601]],

        [[0.6385, 0.0033],
         [0.9620, 0.6817],
         [0.3584, 0.6500]],

        [[0.8129, 0.6471],
         [0.9339, 0.2145],
         [0.3781, 0.7209]],

        [[0.6394, 0.5116],
         [0.2099, 0.3615],
         [0.8517, 0.9323]]])

In [26]:
random_tensor.ndim

3

In [27]:
# create random tesnor with same shape as that of an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)