<a href="https://colab.research.google.com/github/greeshmaunni1990/PyTorch-For-ML-and-DL/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('HEllo world')

HEllo world


In [ ]:
!nvidia-smi

Thu Oct 20 12:17:19 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors

**Creating tensors**

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])

In [ ]:
# dimension can be easily calculated by the number of square brackets.
# if it is has one square brack then it is 1-D
# if it has two square brack then it is 2-D

vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[1, 2], [3, 4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.dtype

torch.int64

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX[1]

tensor([3, 4])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [5, 7, 3],
                        [11, 58, 36]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 5,  7,  3],
         [11, 58, 36]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[[[[2, 11, 36.5], [58, 33, 26]]]]]])
TENSOR

tensor([[[[[[ 2.0000, 11.0000, 36.5000],
            [58.0000, 33.0000, 26.0000]]]]]])

In [ ]:
TENSOR.sh

torch.Size([1, 1, 1, 1, 2, 3])

### Random Tensors

Random numbers are important bacause the way manu neural networks learn is that they start with tensors full of random numbers and then they adjust these random numbers to better represent data
```
Start with random numbers -> look at data -> update random numbers -> look at data > update random numers
```




In [ ]:
# create random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9800, 0.6054, 0.8026, 0.0343],
        [0.0970, 0.6070, 0.7544, 0.7364],
        [0.2915, 0.1384, 0.2273, 0.1726]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create random tensors
random_tensor = torch.rand(4, 3, 2)
random_tensor

tensor([[[0.2608, 0.8707],
         [0.2013, 0.2617],
         [0.3751, 0.7620]],

        [[0.9664, 0.3226],
         [0.1982, 0.1741],
         [0.4060, 0.7445]],

        [[0.2555, 0.9798],
         [0.9910, 0.1187],
         [0.7538, 0.0531]],

        [[0.9404, 0.1393],
         [0.6420, 0.7645],
         [0.3438, 0.5818]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create random tesnor with same shape as that of an image
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

NameError: ignored

In [ ]:
import cv2
import numpy as np
url = 'http://10.39.2.155:8080/video'
cp = cv2.VideoCapture(url)
print('cp', cp)
while(True):
    camera, frame = cp.read()
    if frame is not None:
        cv2.imshow("Frame", frame)
    q = cv2.waitKey(1)
    if q==ord("q"):
        break
cv2.destroyAllWindows()

cp < cv2.VideoCapture 0x7fbec4f2e7d0>


KeyboardInterrupt: ignored

In [ ]:
import requests
import cv2
import numpy as np
import imutils
  
# Replace the below URL with your own. Make sure to add "/shot.jpg" at last.
url = "http://10.39.2.155:8080/video/shot.jpg"
  
# While loop to continuously fetching data from the Url
while True:
    img_resp = requests.get(url)
    img_arr = np.array(bytearray(img_resp.content), dtype=np.uint8)
    img = cv2.imdecode(img_arr, -1)
    img = imutils.resize(img, width=1000, height=1800)
    cv2.imshow("Android_cam", img)
  
    # Press Esc key to exit
    if cv2.waitKey(1) == 27:
        break
  
cv2.destroyAllWindows()

ConnectionError: ignored